### ISSUE TITLE
Tagged releases?

### ISSUE THREAD

**Issue by ghost** [ThanabordeeN/Screenshot_LLM#4]
Hi,

Do you plan to implemented tagged releases?

Thanks!

**Comment by ThanabordeeN** [comment]
Thank for paying your time on this project i just created for your request 😊

**Comment by ghost** [comment]
Thank you! I've enjoyed working on it! I've actually got another PR in the making to address some cosmetic discrepancies like the Main window button size. QT seem to be very finicky when working with richtext, etc. The size difference in the emojii characters I think causes it.
